### ISSUE TITLE
How i can detect if count down view is finished or not 

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [alexfu/CountDownView#15]
hi i can't find Onfinish method 
```
countDownView = findViewById(R.id.count_down);
countDownView.start();
```

**Comment by Qup42** [comment]
You can attach a listener to the countdown view with `CountDownView.setListener(CountDownListener listener)`. The related interface has only one method `onFinishCountDown()` which will get called when the Countdown has finished.

You could do something like this:
```java
countDownView.setListener(new CountDownListener() {
    @Override
    public void onFinishCountDown() {
        //code to run when CountDown has finished
    }
});
```

**Comment by alexfu** [comment]
@Qup42 Thanks for responding. I'll go ahead and close this issue.

**Comment by akhileshsharma** [comment]
Issue is closed but fact is there is no option to setListener.  Above suggestion does not work.

**Comment by alexfu** [comment]
@akhileshsharma Apologies, I just created a new tag (0.2.0) that has the latest updates.
