### ISSUE TITLE
How to change text color

### ISSUE THREAD

**Issue by ben-j69** [alexfu/CountDownView#18]
I would like to display the text in a special color to fit my app, how to do it please ?

**Comment by TarekDeeb** [comment]
Take note of what the value is in `android:textAppearance` in the XML layout, then go to res/values/styles.xml and add this entry

```
<style name="CountDownView" parent="TextAppearance.AppCompat.Display3">
        <item name="android:textColor">#FFFFFF</item>
</style>
```

Change the parent to whatever the value of `android:textAppearance` is. You can also change the name to whatever you like.
Then, go back to the XML layout, and change the value of `textAppearance` to `@style/ContDownView`

eg: `android:textAppearance="@style/CountDownView"`

What this does, is implement a custom style that inherits whatever style you have, and allows you to customize it. You can also add other items in the style to further customize it.

**Comment by alexfu** [comment]
@ben-j69 take a look at the example: https://github.com/alexfu/CountDownView/blob/master/app/src/main/res/layout/activity_main.xml#L16.
