### ISSUE TITLE
IDE can't find Library, please have a look into this matter and respond to me asap

### ISSUE THREAD

**Issue by mrkamiali** [alexfu/CountDownView#20]
IDE can't find Library, please have a look into this matter and respond to me asap,
Plus I need only minutes and seconds view, is there any way to accomplish this thing 00:00 (mm:ss)
![image](https://user-images.githubusercontent.com/16431158/53361046-fb727b80-3958-11e9-81cd-ee662d51c1b7.png)

**Comment by alexfu** [comment]
@mrkamiali your screenshot looks like you might have issues downloading other dependencies? (the firebase ones).

Also, this library is served from jitpack so make sure to have

```
repositories {
  maven { url 'https://jitpack.io' }
}
```

in your `build.gradle`.
