### ISSUE TITLE
Jitpack

### ISSUE THREAD

**Issue by alexfu** [alexfu/CountDownView#4]
Add support for Jitpack

**Comment by daksh143** [comment]
Can you please tell me how to compile this library on Gradle app module?
I couldn't find any compile code line in description.
Or can you guide me how to implement it manually by downloading zip?

**Comment by felipecaldas** [comment]
Agreed with comment above

**Comment by chenjunqi** [comment]
Agreed with comment above too .

**Comment by stormlei** [comment]
+1 @alexfu
